# Generated by Django 5.1.7 on 2025-06-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
