# Generated by Django 5.1.7 on 2025-06-13 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_orderupdate_paid_orders_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='payment_id',
            new_name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='orderupdate',
            name='order_id',
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.orders'),
            preserve_default=False,
        ),
    ]
