# Generated by Django 5.1.7 on 2025-06-13 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_payment_id_orders_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.orders'),
        ),
    ]
