# Generated by Django 5.1.7 on 2025-06-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_orderupdate_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='razorpay_payment_id',
        ),
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='items_json',
            field=models.TextField(),
        ),
    ]
